ALTER TABLE fichas ALTER COLUMN observador TYPE TEXT;
ALTER TABLE fichas ALTER COLUMN club TYPE TEXT;
ALTER TABLE fichas ALTER COLUMN id TYPE TEXT;
ALTER TABLE clubes ALTER COLUMN id TYPE TEXT;
ALTER TABLE observadores ALTER COLUMN id TYPE TEXT;
ALTER TABLE categorias ALTER COLUMN id TYPE TEXT;
