import type { FichaJugadora } from '../types'

export const defaultFichaFields = (): Partial<FichaJugadora> => ({
  fechaPartido: new Date().toISOString().split('T')[0],
  equipo: '',
  categoria: '1ª REF',
  local: '',
  visitante: '',
  observador: '',
  nombre: '',
  primerApellido: '',
  segundoApellido: '',
  fechaNacimiento: '',
  dorsal: 0,
  lateralidad: 'DIESTRA',
  tipologia: 'ATLÉTICA',
  altura: '1.65',
  club: '',
  foto: null,
  fuerza: 5,
  velocidad: 5,
  resistencia: 5,
  minutosJugados: 0,
  partidosTitular: 0,
  partidosSuplente: 0,
  goles: 0,
  tarjetasAmarillas: 0,
  tarjetasRojas: 0,
  demarcacion: 'CENTRAL',
  otraDemarcacion: '',
  evaluacionTecnica: { item1: 3, item2: 3, item3: 3, item4: 3, item5: 3, item6: 3 },
  valoracionGeneral: 3,
  propuesta: 'SEGUIR',
  descripcionJugadora: '',
  observaciones: '',
  cierre: '',
  valoraciones: [],
})
